rl_menu_link.rl_menu_link_experiment.*:
  type: config_entity
  label: 'RL Menu Link experiment'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    menu_link_plugin_id:
      type: string
      label: 'Menu link plugin ID'
    variants:
      type: sequence
      label: 'Variant labels'
      sequence:
        type: string
        label: 'Variant'
    enabled:
      type: boolean
      label: 'Enabled'
