services:

  drupal-lint:
    image: composer:2.7
    profiles: ["lint"]
    working_dir: /src
    command: bash -c "./scripts/run-drupal-lint.sh"
    environment:
      TARGET_DRUPAL_CORE_VERSION: 10
    volumes:
      - .:/src

  drupal-lint-auto-fix:
    image: composer:2.7
    profiles: ["lint"]
    working_dir: /src
    command: bash -c "./scripts/run-drupal-lint-auto-fix.sh"
    environment:
      TARGET_DRUPAL_CORE_VERSION: 10
    volumes:
      - .:/src

  drupal-check:
   image: composer:2.7
   profiles: ["lint"]
   working_dir: /
   command: bash -c "/src/scripts/run-drupal-check.sh"
   tty: true
   environment:
     DRUPAL_RECOMMENDED_PROJECT: 10.3.x-dev
   volumes:
      - .:/src 
